# elasticsearch.yml

example_idx_name: "example_index"
dev_idx_name: "dev_index"
idx_name: "podcast"
idx_limit: 10
hosts: "https://localhost:9200/"
http_crt: "http_ca.crt"
default_clip_sec: 120
idx_info_path: "es/data/index_info"
metadata_tsv_path: "es/data/metadata/metadata.tsv"
podcasts_transcripts_path: "es/data/podcasts-no-audio-13GB/spotify-podcasts-2020/podcasts-transcripts"