name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r es/requirements.txt
        pip install -r backend/requirements.txt

#    - name: Run tests for backend
#      run: |
#        python -m unittest discover -s backend/tests -p '*_test.py'
#
#    - name: Run tests for Elasticsearch
#      run: |
#        python -m unittest discover -s es/tests -p '*_test.py'